# Generated by Django 3.0.2 on 2020-01-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='presetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('initvec', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='rotorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_map', models.CharField(max_length=26)),
                ('turnoverPos', models.CharField(max_length=4)),
                ('notchPos', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=8)),
                ('preset', models.CharField(max_length=16)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enigma.presetModel')),
            ],
        ),
        migrations.CreateModel(
            name='reflectorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_map', models.CharField(max_length=26)),
                ('name', models.CharField(max_length=8)),
                ('preset', models.CharField(max_length=16)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enigma.presetModel')),
            ],
        ),
    ]
